Test docker image

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -6,7 +6,7 @@ on:
         default: ''
 
 jobs:
-  run_pipeline:
+  Build-push-deploy:
     runs-on: ubuntu-latest
 
     steps:
@@ -30,69 +30,80 @@ jobs:
       - name: Use gcloud CLI
         run: gcloud info
 
-      # Install dependencies and run the scripts
-      - name: Install dependencies
-        run: |
-          python -m pip install --upgrade pip
-          pip install -r requirements.txt
+      
+      # - name: Install dependencies
+      #   run: |
+      #     python -m pip install --upgrade pip
+      #     pip install -r requirements.txt
 
-      - name: Run data pipeline - FRED to Cloud SQL
-        env:
-          FRED_API_KEY: ${{ secrets.FRED_API_KEY }}
-          INSTANCE_CONNECTION_NAME: ${{ secrets.INSTANCE_CONNECTION_NAME }}
-          DB_USER: ${{ secrets.DB_USER }}
-          DB_PASS: ${{ secrets.DB_PASS }}
-          DB_NAME: ${{ secrets.DB_NAME }}
-        run: |
-          python fred_to_db.py
+      # - name: Run data pipeline - FRED to Cloud SQL
+      #   env:
+      #     FRED_API_KEY: ${{ secrets.FRED_API_KEY }}
+      #     INSTANCE_CONNECTION_NAME: ${{ secrets.INSTANCE_CONNECTION_NAME }}
+      #     DB_USER: ${{ secrets.DB_USER }}
+      #     DB_PASS: ${{ secrets.DB_PASS }}
+      #     DB_NAME: ${{ secrets.DB_NAME }}
+      #   run: |
+      #     python fred_to_db.py
 
-      - name: Create artifact directory
-        run: mkdir -p artifacts
+      # - name: Create artifact directory
+      #   run: mkdir -p artifacts
 
-      - name: Run data pipeline - Cloud SQL to CSV
-        env:
-          DB_USER: ${{ secrets.DB_USER }}
-          DB_PASS: ${{ secrets.DB_PASS }}
-          DB_NAME: ${{ secrets.DB_NAME }}
-          INSTANCE_CONNECTION_NAME: ${{ secrets.INSTANCE_CONNECTION_NAME }}
-        run: |
-          python db_to_artifacts.py
+      # - name: Run data pipeline - Cloud SQL to CSV
+      #   env:
+      #     DB_USER: ${{ secrets.DB_USER }}
+      #     DB_PASS: ${{ secrets.DB_PASS }}
+      #     DB_NAME: ${{ secrets.DB_NAME }}
+      #     INSTANCE_CONNECTION_NAME: ${{ secrets.INSTANCE_CONNECTION_NAME }}
+      #   run: |
+      #     python db_to_artifacts.py
 
-      - name: Commit artifacts generated by python db_to_artifacts.py
-        run: |
-          git config --local user.email "action@github.com"
-          git config --local user.name "GitHub Action"
-          git add artifacts/
-          git diff-index --quiet HEAD || (git commit -a -m "Add artifacts" --allow-empty --no-verify)
+      # - name: Commit artifacts generated by python db_to_artifacts.py
+      #   run: |
+      #     git config --local user.email "action@github.com"
+      #     git config --local user.name "GitHub Action"
+      #     git add artifacts/
+      #     git diff-index --quiet HEAD || (git commit -a -m "Add artifacts" --allow-empty --no-verify)
           
-      - name: Push artifacts to the main branch
-        uses: ad-m/github-push-action@master
-        with:
-          github_token: ${{ secrets.GITHUB_TOKEN }}
-          branch: main
+      # - name: Push artifacts to the main branch
+      #   uses: ad-m/github-push-action@master
+      #   with:
+      #     github_token: ${{ secrets.GITHUB_TOKEN }}
+      #     branch: main
 
       - name: Authorize Docker push
-        run: gcloud auth configure-docker
+        run: gcloud auth configure-docker --quiet
 
-      - name: Build and tag the docker image
+      - name: Push Docker Image to Container Registry (GCR)
         env:
+          IMAGE_NAME: salesapp
           PROJECT_ID: ${{ secrets.PROJECT_ID }}
-          REPO_NAME: sales_live_dashboard
-          REGION: asia-southeast1
+          GIT_TAG: v0.1.0
         run: |-
-          docker build . --tag gcr.io/$PROJECT_ID/$REPO_NAME:$GITHUB_SHA
+          docker tag $IMAGE_NAME:latest gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
+          docker tag $IMAGE_NAME:latest gcr.io/$PROJECT_ID/$IMAGE_NAME:$GIT_TAG
+          docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
+          docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:$GIT_TAG
 
-      - name: Push the image to the Google Container Registry (GCR)
-        run: |-
-          docker push gcr.io/$PROJECT_ID/$REPO_NAME:$GITHUB_SHA
+      # - name: Build and tag the docker image
+      #   env:
+      #     PROJECT_ID: ${{ secrets.PROJECT_ID }}
+      #     REPO_NAME: sales_live_dashboard
+      #     REGION: asia-southeast1
+      #   run: |-
+      #     docker build . --tag gcr.io/$PROJECT_ID/$REPO_NAME:$GITHUB_SHA
 
-      - name: Cleanup Docker images
-        run: docker image rm gcr.io/$PROJECT_ID/$REPO_NAME:$GITHUB_SHA
+      # - name: Push the image to the Google Container Registry (GCR)
+      #   run: |-
+      #     docker push gcr.io/$PROJECT_ID/$REPO_NAME:$GITHUB_SHA
 
-      - name: Deploy
-        run: |-
-          gcloud run deploy $REPO_NAME \
-          --region $REGION \
-          --image gcr.io/$PROJECT_ID/$REPO_NAME:$GITHUB_SHA \
-          --platform "managed" \
-          --quiet
+      # - name: Cleanup Docker images
+      #   run: docker image rm gcr.io/$PROJECT_ID/$REPO_NAME:$GITHUB_SHA
+
+      # - name: Deploy
+      #   run: |-
+      #     gcloud run deploy $REPO_NAME \
+      #     --region $REGION \
+      #     --image gcr.io/$PROJECT_ID/$REPO_NAME:$GITHUB_SHA \
+      #     --platform "managed" \
+      #     --quiet
